image: node:16

stages:
  - build

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build
  only:
    - main  # Change to the branch you want to deploy

pages:
  stage: deploy
  script:
    - mv build public  # GitLab Pages serves the 'public' directory
  artifacts:
    paths:
      - public
  only:
    - main  # Change to the branch you want to deploy