name: Github Actions Flow
run-name: Deployment to Master
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:  
          node-version: '22'

      - name: Install dependencies
        run: npm install
  
      - name: Build the project
        run: npm run build

      - name: Deploy to Github Pages
        run: |
          git config --global user.email "phillipacooper0@gmail.com"
          git config --global user.name "Phillipa Cooper"
          npm run deploy
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}